anthonyjgrove/react-google-login

src/google.js

Allows the `<GoogleLogin>` element to render as a tag other than `<button>`. Another common desire is to display the `<GoogleLogin>` as an `<a>` tag.

Allow use of custom html tag. Default to "<button>"

---

package.json

I take a look how dependencies defined in `@types`, and looks like best practice here - define dependency with wildcard, because if in `node_modules` we got two different version of one definition (for example react) typescript become mad.
package.json of `@types/react-redux`
```
{
"name": "@types/react-redux",
"dependencies": {
"@types/react": "*",
"@types/redux": "*"
}
}
```

Use version as used in DefinitelyTyped packages.

---

src/index.js

I'm primarily using this param for accessing the REST API from my Google App Script, but there's a lot more it can be used for
Check out: [https://developers.google.com/discovery/v1/using](https://developers.google.com/discovery/v1/using
)
- React.PropTypes.array
- no default

Added support for discoveryDocs from props

---

demo/index.js
src/index.js

Hi,
I encountered the problem using multiple GoogleLogin component with different scopes, for example one for Analytics and one for Adwords.
In the existing master the will both refer to the same scope.
It seems to be fixed by replacing the scope as options from auth2.init to auth2.signIn
Let me know what you think.

Usage of different scopes by multiple GoogleLogin component issue fix

---

index.d.ts

`prompt` is in the `PropTypes` but not the `.d.ts`, leading to typescript compiler errors.

Add `prompt` to `GoogleLoginProps` on index.d.ts

---

README.md
demo/index.js
index.d.ts
src/index.js

I barely know JS, so this change can eat your kitten blabla, but anyway: there is no need to have specific property for offline access, we can determine it from responseType, especially that google can't return both code & access_token/id_token.
Description of responseType in README is rather bad, but I can't come up with something better.  
First commit is from https://github.com/anthonyjgrove/react-google-login/pull/82: I don't really know if this PR will be merged, but I assume both commits can be squashed if it is.

Use responseType to determine if `.grantOfflineAccess()` should be used

---

index.d.ts

In the process of transitioning to use responseType to infer if offline access is needed (https://github.com/anthonyjgrove/react-google-login/commit/14e7213cde9f681b1c2083ffa230cb25f7a5f499), I noticed that the type for the `responseType` param does not exist.
I would prefer to be more strict ie: `readonly responseType?: 'code',` but I'm not 100% sure if that is correct.

Add responseType to GoogleLoginProps typings

---

index.d.ts

Avoids breaking backwards compatibility with `import GoogleLogin from 'react-google-login'`

Fix for TS1319

---

index.d.ts

see: https://github.com/anthonyjgrove/react-google-login/pull/107/files#diff-b52768974e6bc0faccb7d4b75b162c99L71

Typescript: Add responseType back after it was removed in #107

---

src/GoogleLogin.js

When I was using `responseType="code"`, my server still wasn't working correctly for `offline` mode. Google developer docs says:
```
Recommended. Indicates whether your application can refresh access tokens when the user is not present at the browser. Valid parameter values are online, which is the default value, and offline.
Set the value to offline if your application needs to refresh access tokens when the user is not present at the browser. This is the method of refreshing access tokens described later in this document. This value instructs the Google authorization server to return a refresh token and an access token the first time that your application exchanges an authorization code for tokens. 
```
This is available at https://developers.google.com/identity/protocols/OAuth2WebServer …

Pass access_type: offline parameter when responseType === "code"

---

README.md
src/GoogleLogin.js

decouple the accessType and responseType parameters. Getting a refresh token is optional.
By default, access_type is "online" and "offline" access can be requested.

de-couple accessType and responseType

---

index.d.ts

Add reloadAuthResponse to GoogleLoginResponse type definition

---

index.d.ts

`clientId` is defined in the GoogleLogout propTypes but is missing in the TypeScript GoogleLogoutProps interface

Add missing clientId to GoogleLogoutProps

---

index.d.ts

Props are always provided for custom render functions.
Login: https://github.com/anthonyjgrove/react-google-login/blob/master/src/google-login.js#L128
Logout: https://github.com/anthonyjgrove/react-google-login/blob/master/src/google-logout.js#L88

Aligning render props type definition with implementation.

---

index.d.ts

Add missing props to GoogleLoginResponse interface in type-definition.

---

index.d.ts

Add the type "onFailure" to interface GoogleLogoutProps to enable "onFailure" with Typescript

Add type "onFailure" to interface GoogleLogoutProps

---

README.md

At least, that's what I got when I tried using this library myself.

Should be response.Zi.id_token, not response.hg.id_token

---

index.d.ts

Tiny fix – looks like this typo showed up in 5.0.6
🙌  Thanks for the component!

Fix onFailure typo in GoogleLogoutProps interface

---

index.d.ts

Regarding this [issue](https://github.com/anthonyjgrove/react-google-login/issues/244) icon is not available as property on `GoogleLogin` component
`icon` prop is added to GoogleLoginProps type definition.

Add icon prop to GoogleLoginProps in type definition

---

src/use-google-login.js

`useState` usually don't reflect immediately, moving the `autoLoad` condition to its own `useEffect` would fix the issue.

Fix autoLoad setting

---

index.d.ts

updating types to include the hooks types
resolves this [issue](https://github.com/anthonyjgrove/react-google-login/issues/303)

adding typescript types for hooks

---

README.md

Google will not return refresh token when a user has already consented before.
Alternatively, you can add the query parameters prompt=consent&access_type=offline to the OAuth redirect (see Google's OAuth 2.0 for Web Server Applications page).
This will prompt the user to authorize the application again and will always return a refresh_token.
https://stackoverflow.com/a/10857806/5117552

Polish the documentation

---

src/use-google-login.js
src/use-google-logout.js

Current functionality has a race condition if the signOut call is used before the auth2.init() is not finished 
example: 
```javascript 
const { signOut, loaded } = useGoogleLogout({
clientId,
jsSrc,
onLogoutSuccess: () => {
"we logged out!";
}
});
useEffect(() => {
if (loaded) {
signOut();
}
}, [loaded, signOut]);
```
would fail and the onLogoutSuccess would never be called

Bugfix async race condition

---

src/google-login.js
src/load-script.js

The <GoogleLogin /> component sets a jsSrc prop by default, but the useGoogleLogin hook does not. This pr standardizes that behavior by setting a default jsSrc in load-script.js, with optional override on a component/hook basis. Addresses #318

Use a default jsSrc instead of requiring manual set

---

package.json
src/remove-script.js

I am using next.js with next/head and subheads will manipulate the main head tag removing the script before button unmounts. This causes a bug when calling parentNode on a nonexisting element. So added a check to make sure it is there.

Make sure element exists

---

src/use-google-login.js

We need to make sure that the component was not unmounted before loadScript completes loading remote script and triggering its callback.

Added unmount check - to avoid update on umounted component

---

README.md
stories/google-login-notes.md
stories/google-logout-notes.md

First, thanks for the lib.
I think there is some mistakes in the ReadMe regarding the description of the props `jsSrc` and `hostedDomain`. The `jsSrc` description should be the URL where the script is usually hosted, while `hostedDomain` should be the G-suited domain the auth function is limited to https://developers.google.com/identity/sign-in/web/reference#gapiauth2clientconfig.

doc: correct docs around jsSrc and hostedDomain

---

src/use-google-login.js
src/use-google-logout.js

Fixes #340
GoogleAuth is defined but not yet initialized completely, we should use the thenable version of it instead.

Await GoogleAuth to finish initialization

---

src/use-google-logout.js

The `signOut` reference returned by `useGoogleLogout()` is unstable, hence it is unusable as a `useEffect()` dependency.

useGoogleLogout: Stabilize signOut reference

---

README.md

The logout default text was listed as "login"

Fix Logout buttonText prop typo in readme

---

package.json

I updated to React 17 today and I received the following warning:
```
warning " > react-google-login@5.1.22" has incorrect peer dependency "react@^16.0.0".
warning " > react-google-login@5.1.22" has incorrect peer dependency "react-dom@^16.0.0".
```
However, the package seems to work with the latest React, at least for my usage of it. Here are the release notes: https://reactjs.org/blog/2020/10/20/react-v17.html

Update peer dependencies to support React 17

---

src/load-script.js
src/use-google-login.js
src/use-google-logout.js

It's for https://github.com/anthonyjgrove/react-google-login/issues/400.
Just listen to the error event of loading script and trigger `onFailure` if loading failed.

Trigger onFailure while api.js load failed

---

index.d.ts

Adds optional `includeAuthorizationData` boolean to getAuthResponse in the GoogleLoginResponse interface to match the underlying type in the Google API ([API documentation here](https://developers.google.com/identity/sign-in/web/reference#googleusergetauthresponseincludeauthorizationdata))
Currently, it is necessary to use a `@ts-ignore` directive when using the argument

Add optional argument to getAuthResponse

---

README.md
index.d.ts
src/google-login.js
src/google-logout.js
src/use-google-login.js
src/use-google-logout.js

I want to know when the script loading has failed for google logout, but I need to be able to differentiate this from a failure trying to _call_ logout. 
For example, if a user tries to logout and it fails, we show them an error toast - this doesn't make sense when the script has failed to load.
This PR adds a new function for script loading specifically, but defaults to the current failure handler - meaning that this shouldn't be a breaking change 🙏

Add 'onScriptLoadFailure' function to useGoogleLogout hook
